### ISSUE TITLE
support non-divs for smartloading

### ISSUE THREAD

**Issue by aktau** [thybag/PJAX-Standalone#19]
My main content is in a <main> html5 tag, not a div, perhaps this could be supported too? To even load the content, I had to add an id, which I can live with (<main id="content">), but the smartloading doesn't work because it looks for divs only.

**Comment by thybag** [comment]
Hello,

I've just pushed a fix to the develop branch ( https://github.com/thybag/PJAX-Standalone/tree/develop ) which should hopefully resolve this issue.

Thanks,
Carl

**Comment by thybag** [comment]
Edit: as a complete unrelated note, i just had a poke around your site & noticed "strive" was spelled "strife" if your C.V - probably doesn't matter but thought i may as well let you know.

**Comment by aktau** [comment]
You're completely right, very good catch, thanks a lot! If I hadn't already starred PJAX-Standalone, I'd do it now ;).

**Comment by thybag** [comment]
Fix should now be in master :)
