### ISSUE TITLE
Add possibility to read XHR headers in events

### ISSUE THREAD

**Issue by elbebass** [thybag/PJAX-Standalone#23]
We use this for transfering additional information like active menu id, which isn't part of the loaded content.

**Comment by thybag** [comment]
Hello,

I've just pushed an initial implementation of this feature to the develop branch: https://github.com/thybag/PJAX-Standalone/tree/develop

In the develop code, header data should now be returned as an object accessible from PJAX-standalone events in `event.data.headers`.

**Comment by elbebass** [comment]
Thanks for this feature.
