### ISSUE TITLE
Add google tag manager to fire with pjax request

### ISSUE THREAD

**Issue by raunakkathuria** [thybag/PJAX-Standalone#4]
Hi

Can you please provide the mechanism to how to fire google tag manager script on pjax request.

Regards
Raunak

**Comment by thybag** [comment]
Hello,

It depends exactly what you wish to track, but in theory you could just add the code to the complete callback

```
pjax.connect({
    'container': 'content',
    'complete': function(){
        // Google tag manager code here
    }
});
```
